[package]
name = "toy_blockchain"
version = "0.1.0"
authors = ["Travis Haley <thaley@dlr360.com>"]
edition = "2018"

[dependencies]
time = "0.1.42"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
sha2 = "0.8.0"
